#pragma once

#define VERSION_TO_STRING_HELPER(v) #v
#define VERSION_TO_STRING(v) VERSION_TO_STRING_HELPER(v)

#define PRAXIS3D_COMMIT_DATE_YEAR 2024
#define PRAXIS3D_COMMIT_DATE_MONTH 04
#define PRAXIS3D_COMMIT_DATE_DAY 06

#define PRAXIS3D_VERSION_MAJOR 0
#define PRAXIS3D_VERSION_MINOR 2
#define PRAXIS3D_VERSION_PATCH 6

#define PRAXIS3D_COMMIT_DATE ((PRAXIS3D_COMMIT_DATE_YEAR << 16) | (PRAXIS3D_COMMIT_DATE_MONTH << 8) | PRAXIS3D_COMMIT_DATE_DAY)
#define PRAXIS3D_COMMIT_DATE_STRING VERSION_TO_STRING(PRAXIS3D_COMMIT_DATE_YEAR) "-" VERSION_TO_STRING(PRAXIS3D_COMMIT_DATE_MONTH) "-" VERSION_TO_STRING(PRAXIS3D_COMMIT_DATE_DAY)

#define PRAXIS3D_VERSION ((PRAXIS3D_VERSION_MAJOR << 16) | (PRAXIS3D_VERSION_MINOR << 8) | PRAXIS3D_VERSION_PATCH)
#define PRAXIS3D_VERSION_STRING VERSION_TO_STRING(PRAXIS3D_VERSION_MAJOR) "." VERSION_TO_STRING(PRAXIS3D_VERSION_MINOR) "." VERSION_TO_STRING(PRAXIS3D_VERSION_PATCH)